name: random-code-snippet
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
            filename: src/random-code-snippet.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_code: yes
            plugin_code_load: 400
            plugin_code_visibility: public
