name: stars
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
jobs:
  followers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: src/stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 5
