name: WakaTime
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
jobs:
  waka-time:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: src/wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
